# Generated by Django 4.1.5 on 2023-09-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
    ]
